// Pre-tokenized code snippets shown in the right-hand viewer.
//
// Each snippet's `anchors` map names a row index that main.js can
// `viewer.fire("snippet", "anchor")` to highlight as the pipeline runs.

export const SNIPPETS = {
  device: {
    title: "1 · device.js",
    lines: [
      "// On boot, the buds firmware generates an Ed25519 keypair once,",
      "// stores the private key in its Secure Element, and pushes the",
      "// public key to the server during pairing.",
      "",
      "const kp = loadOrCreateKeypair();              // 32-byte private, 32-byte public",
      "const deviceId = 'buds-sim-' + kp.publicB64.slice(0, 8);",
      "",
      "await registerDevice(deviceId, kp.publicB64);  // POST /v1/devices/register",
    ],
    anchors: { register: 7 },
  },

  mic: {
    title: "2 · mic.js",
    lines: [
      "// Mic capture — the only sensor real buds have for ANC & AI input.",
      "// Browser stand-in: Web Audio mic → 16 kHz mono Int16 (matching buds).",
      "",
      "async start() {",
      "  const stream = await navigator.mediaDevices.getUserMedia({ audio: {",
      "    echoCancellation: false, noiseSuppression: false, autoGainControl: false,",
      "  } });",
      "  this.ctx = new AudioContext();",
      "  this.source = this.ctx.createMediaStreamSource(stream);",
      "  this.processor.onaudioprocess = e => {",
      "    const i16 = downsampleAndQuantize(e.inputBuffer.getChannelData(0),",
      "                                       this.ctx.sampleRate, 16000);",
      "    for (const l of this.sampleListeners) l(i16);",
      "  };",
      "}",
    ],
    anchors: { getusermedia: 4 },
  },

  ringbuffer: {
    title: "3 · ring-buffer.js",
    lines: [
      "// Dual ring buffer · A=환경음 30s 룩백 · B=사용자 질문 5s.",
      "// Write hot-path: O(1) modulo arithmetic, no allocations.",
      "",
      "write(int16) {",
      "  let src = 0, dst = this.writeIdx, cap = this.capacity;",
      "  while (src < int16.length) {",
      "    const take = Math.min(cap - dst, int16.length - src);",
      "    this.buf.set(int16.subarray(src, src + take), dst);",
      "    src += take;  dst = (dst + take) % cap;",
      "  }",
      "  this.writeIdx = dst;",
      "  this.filled = Math.min(cap, this.filled + int16.length);",
      "}",
      "",
      "snapshot() {                       // linearize oldest → newest",
      "  if (this.filled < this.capacity) return this.buf.slice(0, this.filled);",
      "  const out = new Int16Array(this.capacity);",
      "  const head = this.writeIdx;",
      "  out.set(this.buf.subarray(head), 0);",
      "  out.set(this.buf.subarray(0, head), this.capacity - head);",
      "  return out;",
      "}",
    ],
    anchors: { writeA: 3, snapshot: 14 },
  },

  trigger: {
    title: "4 · trigger.js",
    lines: [
      "// Long-press detected. Two actions in lockstep:",
      "//   (1) latch the current write position of A (so subsequent",
      "//       writes don't pollute what we're about to send),",
      "//   (2) start a fresh encoder on Buffer B for the user's question.",
      "",
      "function startQuestion() {",
      "  ringB.reset();",
      "  recording = true;",
      "  questionStartTs = performance.now();",
      "  lastVoiceTs = questionStartTs;",
      "  viewer.fire('trigger', 'longpress');",
      "}",
    ],
    anchors: { longpress: 6 },
  },

  vad: {
    title: "5 · vad.js",
    lines: [
      "// Voice Activity Detection — only used to KNOW when the user",
      "// finished speaking. Never used as a wake-word (privacy first).",
      "//   Active   = RMS > 0.012",
      "//   Endpoint = 500ms continuous silence",
      "//   Hard cap = 5s",
      "",
      "if (rms > VAD_RMS_THRESHOLD) {",
      "  lastVoiceTs = performance.now();             // still speaking",
      "} else if (performance.now() - lastVoiceTs > 500) {",
      "  finishQuestion('vad');                       // endpoint detected",
      "} else if (performance.now() - questionStartTs > 5000) {",
      "  finishQuestion('max');                       // hard cap",
      "}",
    ],
    anchors: { speech: 6, endpoint: 8 },
  },

  packet: {
    title: "6 · packet.js",
    lines: [
      "// Build envelope, then sign with Ed25519. Canonical-bytes spec",
      "// is shared verbatim with the Python server (shared/python/packet.py)",
      "// so the signature is byte-for-byte verifiable.",
      "",
      "const aBytes = ringA.asBytes();         // 30s snapshot (read-only fan-out)",
      "const bBytes = ringB.asBytes();         // user question",
      "",
      "const envelope = buildEnvelope({",
      "  deviceId, sessionId, trigger: 'long_press',",
      "  lookbackBytes: aBytes, questionBytes: bBytes,",
      "  lookbackMs:    floor(ringA.filled / 16000 * 1000),",
      "  questionMs:    floor(ringB.filled / 16000 * 1000),",
      "});",
      "",
      "const signed = signEnvelope(envelope, kp);  // sets envelope.sig",
    ],
    anchors: { snapshot: 5, build: 8, sign: 15 },
  },

  api: {
    title: "7 · api.js",
    lines: [
      "// POST the signed envelope to the server. The server's auth",
      "// middleware:  (1) reads X-Device-Id  (2) looks up pubkey",
      "//              (3) recomputes canonical bytes  (4) ed25519.verify",
      "// Anything mismatched → 401.",
      "",
      "async function postSession(deviceId, signedEnvelope) {",
      "  const r = await fetch(apiBase() + '/v1/sessions', {",
      "    method: 'POST',",
      "    headers: { 'Content-Type': 'application/json',",
      "               'X-Device-Id': deviceId },",
      "    body: JSON.stringify(signedEnvelope),",
      "  });",
      "  return await r.json();",
      "}",
      "",
      "// Then subscribe to the SSE stream for stage-by-stage updates.",
      "function streamSession(sessionId, { onStage, onEnd }) {",
      "  const es = new EventSource('/v1/stream/' + sessionId);",
      "  es.addEventListener('stage', e => onStage(JSON.parse(e.data)));",
      "  es.addEventListener('end',   () => { onEnd(); es.close(); });",
      "}",
    ],
    anchors: { post: 6, stream: 17 },
  },

  server: {
    title: "8 · server.py (mocked pipeline)",
    lines: [
      "# server/src/routes/sessions.py — what the Railway-hosted",
      "# FastAPI runs for each incoming envelope.",
      "",
      "async def _run_mock_pipeline(session_id, body):",
      "    await asyncio.sleep(0.3)",
      "    store.append_event(session_id, {'stage': 'decoded',     ...})",
      "    await asyncio.sleep(0.5)",
      "    store.append_event(session_id, {'stage': 'stt',         ...})",
      "    await asyncio.sleep(0.4)",
      "    store.append_event(session_id, {'stage': 'intent',      ...})",
      "    await asyncio.sleep(0.7)",
      "    store.append_event(session_id, {'stage': 'fingerprint', ...})",
      "    await asyncio.sleep(0.6)",
      "    store.append_event(session_id, {'stage': 'llm_answer',  ...})",
      "    await asyncio.sleep(0.5)",
      "    store.append_event(session_id, {'stage': 'tts',         ...})",
      "    store.mark_done(session_id)",
    ],
    anchors: {
      decoded: 5, stt: 7, intent: 9, fingerprint: 11, llm_answer: 13, tts: 15, complete: 16,
    },
  },
};
